---

version: "2"

run:
  tests: true           # include *_test.go
  timeout: 5m           # optional timeout
  modules-download-mode: readonly

linters:
  enable:
    - gosec
    - revive
    - errcheck
    - govet

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gosec:
      excludes:
        - G306

exclusions:
  generated: lax
  presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
  rules:
    - linters:
        - gosec
      path: _test\.go
  paths:
    - .*\.pb\.go$
    - .*\.gen\.go$
    - ../../go/pkg/mod
    - third_party
    - builtin
    - examples

formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - .*\.gen\.go$
      - ../../go/pkg/mod
      - third_party
      - builtin
      - examples
