---

run:
  skip-dirs:
    - ../../go/pkg/mod
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

linters:
  enable:
    - gofmt
    - govet
    - gosimple
    - staticcheck
    - unused
    - gosec
    - revive
    - errcheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosec:
    excludes:
      - G306  # exclude file permission rule

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec

output:
  format: colored-line-number
