---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"


  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: [-s, .]
        types: [yaml]
        files: \.(yaml|yml)$

  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        description: Formats Go code using 'go fmt'
        entry: make gofmt
        language: system
        types: [go]
        pass_filenames: false
        always_run: true

      - id: gosec
        name: gosec
        description: Inspects source code for security problems by scanning the Go AST
        entry: make gosec
        language: system
        types: [go]
        pass_filenames: false

      - id: go-vet
        name: go-vet
        description: Reports suspicious constructs in Go code that may indicate bugs
        entry: make govet
        language: system
        types: [go]
        pass_filenames: false

      - id: goerrcheck
        name: goerrcheck
        description: Finds unchecked errors in Go code that could lead to error handling bugs
        entry: make goerrcheck
        language: system
        types: [go]
        pass_filenames: false

      - id: golangci
        name: golangci
        description: Run all linters and formatters configured in .golangci.yaml
        entry: make golangci
        language: system
        types: [go]
        pass_filenames: false

      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go that runs linters in parallel
        entry: golangci-lint run
        types: [go]
        language: golang
        require_serial: true
        pass_filenames: false

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker
        name: hadolint
        args: [--failure-threshold=error]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        name: gitleaks
