---

services:
  webgoat:
    image: ghcr.io/happyhackingspace/webgoat:latest
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - network

networks:
  network:
    driver: bridge
