---

services:
  web:
    image: ghcr.io/happyhackingspace/bwapp
    ports:
      - "80:80"
    networks:
      - network
    volumes:
      - data:/app

volumes:
  data:

networks:
  network:
    driver: bridge
