---

services:
  web:
    image: hackersploit/bwapp-docker:latest
    ports:
      - "80:80"
    networks:
      - network
    volumes:
      - data:/app

volumes:
  data:

networks:
  network:
    driver: bridge
