---

services:
  web:
    image: ghcr.io/happyhackingspace/juice-shop:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - network
    volumes:
      - data:/juice-shop/data
      - logs:/juice-shop/logs

volumes:
  data:
  logs:

networks:
  network:
    driver: bridge
