---
name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: "Lint"
    if: "${{ !endsWith(github.actor, '[bot]') }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.23'
      - name: Install tools
        run: |
          go install mvdan.cc/gofumpt@latest
          go install github.com/kisielk/errcheck@latest
          go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run linters
        run: |
          make gofmt
          make golangci
          make govet
          make goerrcheck

  hadolint:
    name: Run Hadolint
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error
