---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/dev-tools:latest
    steps:
      - uses: actions/checkout@v4
      - run: make lint
      - run: make yamllint
      - run: make goerrcheck
      - run: make golangci
      - run: make govet

  hadolint:
    name: Run Hadolint
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error
