---
name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build \
            --target dev-tools \
            -t vulnerable-target .

      - name: Run linters
        run: |
          docker run --rm \
            -v $(pwd):/app \
            -w /app \
            -e CI=true \
            vulnerable-target \
            /bin/bash -c "cd /app && \
              make gofmt \
              make golangci \
              make govet \
              make goerrcheck

  hadolint:
    name: Run Hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error
