---

name: 🔨 Tests
on:
  push:
    branches: ["dev", "main"]
    tags:
      - "v*"
  pull_request:
    paths:
      - "**.go"
      - "**.mod"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    if: ${{ !endsWith(github.actor, '[bot]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.23"
          cache: true

      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m ./...

      - name: Run yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          yamllint_flags: "-d relaxed ."

      - name: Run go vet
        run: go vet ./...

      - name: Install errcheck
        run: go install github.com/kisielk/errcheck@v1.6.3
      - name: Run errcheck
        run: errcheck -ignore '[cC]lose' ./...

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Run gosec
        run: gosec ./...

  release:
    name: "🎉 Release"
    runs-on: ubuntu-latest
    needs: lint
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
