---

name: Validate Templates

on:
  push:
    paths:
      - 'templates/**'
      - 'pkg/templates/**'
      - '.github/workflows/validate-templates.yml'
  pull_request:
    paths:
      - 'templates/**'
      - 'pkg/templates/**'
      - '.github/workflows/validate-templates.yml'
  workflow_dispatch:

jobs:
  validate:
    name: Validate Template Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Build the application
        run: go build -o vt ./cmd/vt

      - name: Validate all templates
        run: ./vt validate

      - name: Verify templates directory structure
        run: |
          echo "Checking templates directory structure..."
          find templates -name "index.yaml" -type f | while read file; do
            echo "Found template: $file"
            template_dir=$(dirname "$file")
            template_name=$(basename "$template_dir")
            # Check if the template directory name matches the ID in index.yaml
            if [ -f "$file" ]; then
              id=$(grep "^id:" "$file" | head -1 | sed 's/id:[[:space:]]*//' | tr -d '\r\n')
              if [ "$id" != "$template_name" ]; then
                echo "❌ Template ID '$id' does not match directory name '$template_name' in $file"
                exit 1
              else
                echo "✅ Template ID '$id' matches directory name '$template_name'"
              fi
            fi
          done

      - name: Check for missing index.yaml files
        run: |
          echo "Checking for missing index.yaml files..."
          find templates -type d -mindepth 1 | while read dir; do
            if [ ! -f "$dir/index.yaml" ]; then
              echo "❌ Missing index.yaml in directory: $dir"
              exit 1
            else
              echo "✅ Found index.yaml in: $dir"
            fi
          done
